version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Europe/Lisbon
    cooldown:
      default-days: 7
    groups:
      javascript-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
    open-pull-requests-limit: 5
